### PR TITLE
Mark required issues as solved

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by dansteen** [comment]
The networking issue was resolved a few weeks back, but when I tested it things were still not quite right.   I'll give it another test.

**Comment by ysangkok** [comment]
What were the results of your test?

**Comment by dansteen** [comment]
@ysangkok We are waiting on this issue to be resolved:  

https://github.com/docker/libcompose/issues/319

Until then, we are basically dead-in-the-water (unfortunately) :-(

**Comment by ysangkok** [comment]
What's the status on this?

**Comment by ysangkok** [comment]
Hey @dansteen , what's the status?

**Comment by dansteen** [comment]
Wow this is a bit of a blast from the past.  Unfortunately, I don't have a use-case for this anymore since we moved to packer to build our containers, but if you want to test it out I'm happy to update the README.

**Comment by ysangkok** [comment]
Closing since it clobbers my PR listing page and I don't think anybody cares about it.

**Pull request closed without merging**
